// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvTrpBhcdltK2l1D6yAoiw7Idcd_dwr94',
    appId: '1:78590313322:web:b26834491dc69f6f58db13',
    messagingSenderId: '78590313322',
    projectId: 'cartwise-49401',
    authDomain: 'cartwise-49401.firebaseapp.com',
    storageBucket: 'cartwise-49401.firebasestorage.app',
    measurementId: 'G-4HN4YP5W2R',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvTrpBhcdltK2l1D6yAoiw7Idcd_dwr94',
    appId: '1:78590313322:web:f2a2f23b4e8a7fe358db13',
    messagingSenderId: '78590313322',
    projectId: 'cartwise-49401',
    authDomain: 'cartwise-49401.firebaseapp.com',
    storageBucket: 'cartwise-49401.firebasestorage.app',
    measurementId: 'G-D11JM3V36D',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1OMLDyCXkaj8bWgObEbLAkKoPBvtF-HU',
    appId: '1:78590313322:ios:515ba0dea88cab3c58db13',
    messagingSenderId: '78590313322',
    projectId: 'cartwise-49401',
    storageBucket: 'cartwise-49401.firebasestorage.app',
    iosBundleId: 'cartwise.firebase.app.macos',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1OMLDyCXkaj8bWgObEbLAkKoPBvtF-HU',
    appId: '1:78590313322:ios:debc0b90955c912258db13',
    messagingSenderId: '78590313322',
    projectId: 'cartwise-49401',
    storageBucket: 'cartwise-49401.firebasestorage.app',
    iosBundleId: 'cartwise.firebase.app.ios',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6GLiAQKHdHwqFl6CybYhsC8GdnyuCBw8',
    appId: '1:78590313322:android:e211504541c946e758db13',
    messagingSenderId: '78590313322',
    projectId: 'cartwise-49401',
    storageBucket: 'cartwise-49401.firebasestorage.app',
  );

}